# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Make build on release

on:
  release: 
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            in_asset: lfs-s3
            out_asset: lfs-s3-linux          # Linux binary
          - os: macos-latest
            in_asset: lfs-s3
            out_asset: lfs-s3-mac           # macOS binary
          - os: windows-latest
            in_asset: lfs-s3.exe
            out_asset: lfs-s3-windows.exe        # Windows binary
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Tidy mod
      run: go mod tidy
    - name: Build
      run: go build -v -ldflags "-s -w"
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }} 
        asset_path: ${{ matrix.in_asset }}
        asset_name: ${{ matrix.out_asset }}
        asset_content_type: application/octet-stream
